services:
  - type: web
    name: youshoes
    env: ruby
    buildCommand: |
      composer install
      npm install && npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/sqlite/db.sqlite
